### PR TITLE
Update all patches for M90

### PR DESCRIPTION
**Pull request by threema-danilo**
Most patches apply on M90:

```
$ ./cli.sh patch
Applying ../../patches/disable-dtmf-and-comfort-noise.patch...
Applying ../../patches/disable-unused-audio-codecs.patch...
Applying ../../patches/dont-leak-video-orientation.patch...
Applying ../../patches/dtls-cipher-suites.patch...
Applying ../../patches/enable-cbr-by-default.patch...
Applying ../../patches/expose-crypto-option-aes-128-sha1-80.patch...
Applying ../../patches/expose-video-capturer-state.patch...
Applying ../../patches/force-dtls-1_2.patch...
Applying ../../patches/only-resolve-uuid-mdns-hostnames.patch...
Applying ../../patches/srtp-cipher-suites.patch...
Applied 10 patches
```

Only one patch needed an update (by applying to M84 and cherry-picking on M90). One patch could be removed, since it was upstreamed.

Three patches don't yet apply, I added an `m84`-suffix for those.

### CODE REVIEW

**Comment by lgrahl** [comment]
Alright, I'll just push the remaining ones onto this branch.

**Comment by lgrahl** [comment]
Should we document the release branch our patches (should) apply successfully with in the readme? I think that would make sense.

**Comment by dbrgn** [comment]
Yeah, maybe it would be good to list the patches in a table, including a one-line summary and the release branches they were tested with.

**Comment by lgrahl** [comment]
Hrm, I'll remove all the old patches if that's okay for you. Pretty sure we're not going to go back and even then we have the history and right now it's kind of a mixed bag (we have removed some patches but not all).

**Comment by dbrgn** [comment]
Sure, fine with me 🙂

**Review by lgrahl — APPROVED** [review]

**Pull request merged**
